FROM node:12-alpine
# Set env
ENV PORT=3000
ENV HOST_ENV=preproduction
ENV BACKEND_HTTP_API_ENDPOINT=https://stockzones-back-pre-prod.scenario-projects.com/
ENV BACKEND_SOCKET_ENDPOINT=wss://localhost:3000
ENV BACKEND_SOCKET_PATH=/backend/socket
ENV USER_IDLE_TIMEOUT_MS=600000
# Create app directory
WORKDIR /frontend
# Installing dependencies
COPY ["package.json","yarn.lock","./"]
RUN yarn
# Copying source files
COPY ./ ./
# Building app
RUN yarn build
EXPOSE 3000
# Running the app
CMD ["yarn", "start"]

